version: '2'
services:
  db: &DB
    image: postgres:9.4.5
    ports:
      - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: sh -c "mix phoenix.server"
    environment:
      DATABASE_URL: ecto://user:password@db/rest_api_dev
    volumes:
        - ./:/usr/src/app
    ports:
      - 4000:4000
    links:
      - db:db
    depends_on:
      - db

  test:
    build: .
    command: sh -c "mix deps.get && mix test"
    environment:
      DATABASE_URL: ecto://user:password@db/rest_api_test
    volumes:
      - ./:/usr/src/app
    links:
      - db:db
